#!/usr/bin/env python
"""
large sum problem

By: A.O.

"""

import sys
import os
import string
import math

def main(argv):
  try:

    numbers = []
    for line in sys.stdin:
      numbers.append(int(line.rstrip(os.linesep)[:12]))

    print "sum = %s" % str(sum(numbers))[:10]

  except "end of file":
    return None
if __name__ == "__main__":
  main(sys.argv)
